### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by thrishik7** [HTTP-APIs/hydra-python-agent-gui#20]
**Python version**: 3.6.8

**Operating system** : Ubuntu 18.04.2 LTS

**Issue**: When I try to run app.py `python3 app.py` such error shows up:

`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f85335a0240>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thrishik/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /serverapi/vocab (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f85335a0240>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 15, in <module>
    agent = Agent(url)
  File "/home/thrishik/hydrus_gsoc/gui/src/hydra-agent/hydra_agent/agent.py", line 30, in __init__
    self.fetch_apidoc()
  File "/home/thrishik/hydrus_gsoc/gui/src/hydra-agent/hydra_agent/agent.py", line 47, in fetch_apidoc
    jsonld_api_doc = super().get(self.entrypoint_url + '/vocab').json()
  File "/home/thrishik/.local/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/thrishik/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/thrishik/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/thrishik/.local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /serverapi/vocab (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f85335a0240>: Failed to establish a new connection: [Errno 111] Connection refused',))`

How do I run app.py successfully?

**Comment by xadahiya** [comment]
Have you run any Hydrus instance?

**Comment by thrishik7** [comment]
I think I ran `hydrus serve`. I will check on this

**Comment by xadahiya** [comment]
Make sure you have hydrus running on 8080

**Comment by Guttz** [comment]
The default config is for the agent to connect to a hydrus server at 'http://localhost:8080/serverapi'. 

Make sure you run hydrus and check if the server is properly working and let us know here if it works.

**Comment by thrishik7** [comment]
**Current progress:**
After running `python3 app.py` by hydrus instance running

I encountered an issue:

```
loading... of graph
creating entrypoint node
split entrypoint into 2 types of endpoints collection and classes
classes endpoint or accessing classes
accessing every collection in entrypoint
commiting
Traceback (most recent call last):
  File "app.py", line 15, in <module>
    agent = Agent(url)
  File "/home/thrishik/hydrus_gsoc/gui/src/hydra-agent/hydra_agent/agent.py", line 31, in __init__
    self.initialize_graph()
  File "/home/thrishik/hydrus_gsoc/gui/src/hydra-agent/hydra_agent/agent.py", line 58, in initialize_graph
    self.graph.main(self.entrypoint_url, self.api_doc, True)
  File "/home/thrishik/hydrus_gsoc/gui/src/hydra-agent/hydra_agent/redis_core/graph_init.py", line 69, in main
    self.redis_graph.commit()
  File "/home/thrishik/hydrus_gsoc/hydra-python-agent/src/redisgraph/redisgraph/graph.py", line 96, in commit
    return self.query(query)
  File "/home/thrishik/hydrus_gsoc/hydra-python-agent/src/redisgraph/redisgraph/graph.py", line 130, in query
    response = self.redis_con.execute_command("GRAPH.QUERY", self.name, q, "--compact")
  File "/home/thrishik/.local/lib/python3.6/site-packages/redis/client.py", line 839, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/thrishik/.local/lib/python3.6/site-packages/redis/client.py", line 853, in parse_response
    response = connection.read_response()
  File "/home/thrishik/.local/lib/python3.6/site-packages/redis/connection.py", line 718, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'GRAPH.QUERY'
```
I think the above issue is raised due to error in docker handling response

When I run `sudo docker run -p 6379:6379 -it --rm redislabs/redisgraph` 

`docker: Error response from daemon: driver failed programming external connectivity on endpoint amazing_driscoll (bd87124119f1e095475ce368a0dfba21111e82e9461dbcb604fc1ae539c6bef2): Error starting userland proxy: listen tcp 0.0.0.0:6379: bind: address already in use.`

what should be done?

**Comment by Guttz** [comment]
> bind: address already in use.

This is related to not being able to run the Redis server. So in the error you posted there's something else at port 6379, maybe even a Redis. 

I would suggest shutting all Redis/what's on port 6379 and debugging until you make redis work by itself with `sudo docker run -p 6379:6379 -it --rm redislabs/redisgraph`.

**Comment by thrishik7** [comment]
okay, now I restarted the redis server

and ran app.py

```

loading... of graph
creating entrypoint node
split entrypoint into 2 types of endpoints collection and classes
classes endpoint or accessing classes
accessing every collection in entrypoint
commiting
Traceback (most recent call last):
  File "app.py", line 15, in <module>
    agent = Agent(url)
  File "/home/thrishik/hydrus_gsoc/gui/venv/src/hydra-agent/hydra_agent/agent.py", line 31, in __init__
    self.initialize_graph()
  File "/home/thrishik/hydrus_gsoc/gui/venv/src/hydra-agent/hydra_agent/agent.py", line 58, in initialize_graph
    self.graph.main(self.entrypoint_url, self.api_doc, True)
  File "/home/thrishik/hydrus_gsoc/gui/venv/src/hydra-agent/hydra_agent/redis_core/graph_init.py", line 69, in main
    self.redis_graph.commit()
  File "/home/thrishik/hydrus_gsoc/gui/venv/src/redisgraph/redisgraph/graph.py", line 96, in commit
    return self.query(query)
  File "/home/thrishik/hydrus_gsoc/gui/venv/src/redisgraph/redisgraph/graph.py", line 130, in query
    response = self.redis_con.execute_command("GRAPH.QUERY", self.name, q, "--compact")
  File "/home/thrishik/hydrus_gsoc/gui/venv/lib/python3.6/site-packages/redis/client.py", line 839, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/thrishik/hydrus_gsoc/gui/venv/lib/python3.6/site-packages/redis/client.py", line 853, in parse_response
    response = connection.read_response()
  File "/home/thrishik/hydrus_gsoc/gui/venv/lib/python3.6/site-packages/redis/connection.py", line 718, in read_response
    raise response
redis.exceptions.ResponseError: errMsg: Invalid input '@': expected a property name, '}' or a parameter line: 1, column: 23, offset: 22 errCtx: CREATE (Entrypoint:id{@id:"vocab:Entrypoint",url:"http://localhost:8080/serve... errCtxOffset: 22

```

**Comment by Guttz** [comment]
I forgot to specify the redis dock version in my comment above, sorry!

It should be as it is in redis_setup.sh

`sudo docker run -p 6379:6379 -it --rm redislabs/redisgraph:2.0-edge`. 

Redisgraph has some breaking changes and the current Agent was developed with version 2.0.

**Comment by thrishik7** [comment]
works fine, Thank you :)
