### ISSUE TITLE
unknown command 'GRAPH.QUERY'

### ISSUE THREAD

**Issue by PrathamDogra** [HTTP-APIs/hydra-python-agent-gui#23]
* I have followed all the steps of README.md  and also the docker image( sudo docker run -p 6379:6379 -it --rm redislabs/redisgraph:2.0-edge) is running.
* But on python3 app.py I am getting the following error.
loading... of graph
creating entrypoint node
split entrypoint into 2 types of endpoints collection and classes
classes endpoint or accessing classes
accessing every collection in entrypoint
commiting
Traceback (most recent call last):
  File "app.py", line 15, in <module>
    agent = Agent(url)
  File "/mnt/c/Users/hp/Desktop/Hydra-Ecosystem/hydra-python-agent-gui/venv/src/hydra-agent/hydra_agent/agent.py", line 31, in __init__
    self.initialize_graph()
  File "/mnt/c/Users/hp/Desktop/Hydra-Ecosystem/hydra-python-agent-gui/venv/src/hydra-agent/hydra_agent/agent.py", line 58, in initialize_graph
    self.graph.main(self.entrypoint_url, self.api_doc, True)
  File "/mnt/c/Users/hp/Desktop/Hydra-Ecosystem/hydra-python-agent-gui/venv/src/hydra-agent/hydra_agent/redis_core/graph_init.py", line 69, in main
    self.redis_graph.commit()
  File "/mnt/c/Users/hp/Desktop/Hydra-Ecosystem/hydra-python-agent-gui/venv/src/redisgraph/redisgraph/graph.py", line 96, in commit
    return self.query(query)
  File "/mnt/c/Users/hp/Desktop/Hydra-Ecosystem/hydra-python-agent-gui/venv/src/redisgraph/redisgraph/graph.py", line 130, in query
    response = self.redis_con.execute_command("GRAPH.QUERY", self.name, q, "--compact")
  File "/mnt/c/Users/hp/Desktop/Hydra-Ecosystem/hydra-python-agent-gui/venv/lib/python3.6/site-packages/redis/client.py", line 878, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/mnt/c/Users/hp/Desktop/Hydra-Ecosystem/hydra-python-agent-gui/venv/lib/python3.6/site-packages/redis/client.py", line 892, in parse_response
    response = connection.read_response()
  File "/mnt/c/Users/hp/Desktop/Hydra-Ecosystem/hydra-python-agent-gui/venv/lib/python3.6/site-packages/redis/connection.py", line 752, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'GRAPH.QUERY'

What should be the appropriate way to resolve this issue.

**Comment by chrizandr** [comment]
Seems like an error caused by Redis. Are you running a hydrus API along with the agent?

**Comment by PrathamDogra** [comment]
The hydrus server is running at http://localhost:8080/serverapi/  and in the hydra-python-agent when I run python hydra_agent/querying_mechanism.py the Command Line Tool is initiated but when enter the http://localhost:8080/serverapi/  (hydrus URL), I got the same error **redis.exceptions.ResponseError: unknown command 'GRAPH.QUERY'**

**Comment by PrathamDogra** [comment]
Machine specifications
OS: WSL Ubuntu18.04 (inside Windows 10 Home)

**Comment by Guttz** [comment]
I've made the whole setup again and everything is working fine here.

![image](https://user-images.githubusercontent.com/11739405/73872781-1e770200-482f-11ea-8c80-0ed358c77826.png)

**Comment by Guttz** [comment]
This is very likely a RedisGraph related problem. I've tried to reproduce the error running other RedisGraphs versions and wasn't able to. Googling I ran into two links:

https://github.com/RedisGraph/RedisGraph/issues/575
https://github.com/RedisGraph/redisgraph-py/issues/24

Please take some time to debug with this info, restarting and installing dependencies again and let us know if you are successful.

**Comment by PrathamDogra** [comment]
Sure, I will try to debug this problem which is most probably due to the default IP address of redis-server.

**Comment by PrathamDogra** [comment]
The redislabs/redisgraph:2.0-edge is running on 0.0.0.0:6379, is this the problem?
@Guttz can I ask you on which IP address your docker container is running is it 127.0.0.1 or 0.0.0.0

**Comment by PrathamDogra** [comment]
The issue got resolved when I removed the image and container and then re-pulled it.
