### ISSUE TITLE
hydra-python-agent-gui fails connecting to agent, sends request to hydra

### ISSUE THREAD

**Issue by chrissweet** [HTTP-APIs/hydra-python-agent-gui#63]
### I'm submitting a 
bug report.

### Current Behaviour:
**Running hydra-python-agent-gui I get**
loading... of graph
creating entrypoint node
split entrypoint into 2 types of endpoints collection and classes
classes endpoint or accessing classes
accessing every collection in entrypoint
commiting
done!!!!
INFO:engineio.client:Attempting polling connection to http://localhost:8080/socket.io/?transport=polling&EIO=3
Traceback (most recent call last):
  File "app.py", line 15, in <module>
    agent = Agent(url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hydra_python_agent-0.0.1-py3.7.egg/hydra_agent/agent.py", line 40, in __init__
    namespaces=namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/python_socketio-4.4.0-py3.7.egg/socketio/client.py", line 270, in connect
    six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
  File "<string>", line 3, in raise_from
socketio.exceptions.ConnectionError: Unexpected status code 404 in server response

**Note that the hydros server shows,**
hydrus_server_1  | ::ffff:172.23.0.1 - - [2020-07-06 14:16:04] "GET /serverapi/vocab HTTP/1.1" 200 26763 0.001701
hydrus_server_1  | ::ffff:172.23.0.1 - - [2020-07-06 14:16:04] "GET /socket.io/?transport=polling&EIO=3&t=1594044964.8984902 HTTP/1.1" 404 388 0.000874

So it gets the graph from hydrus but it seems to query hydros rather than connect to the Agent via the socket.

### Expected Behaviour:
I would be able to brows the hydrus API

### Steps to reproduce:
Running on a MacBook Pro.
1) Run the hydrus docker container, can connect correctly with Postman
2a) Install the agent module, run redis_setup.sh, and run the gui, python3 app.py
2b) Alternatively run the hydra-python-agent docker container and then run the gui, python3 app.py

### Do you want to work on this issue?
Yes

**Comment by chrizandr** [comment]
@priyanshunayan

**Comment by priyanshunayan** [comment]
@chrissweet To run agent-gui, please run hydrus server using CLI. Please follow instructions here: https://github.com/HTTP-APIs/hydrus#demo. Then run the hydrus using `hydrus serve --no-auth`. It will work as expected. Thank you.

**Comment by priyanshunayan** [comment]
@chrissweet Thank you for using GUI. The support for web sockets is yet to be supported by hydrus container. For now, please install hydrus using the instructions here: https://github.com/HTTP-APIs/hydrus#demo and then run hydrus using the command `hydrus serve --no-auth` to skip authentication. This will work as expected.

**Comment by chrissweet** [comment]
Hi Priyanshu,

   Thanks for the fast response! I ran the container as I got this error trying to run with hydra serve,

hydrus serve
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/hydrus", line 11, in <module>
    load_entry_point('hydrus==0.3.1', 'console_scripts', 'hydrus')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hydrus-0.3.1-py3.7.egg/cli.py", line 15, in <module>
    from gevent.pywsgi import WSGIServer
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gevent/__init__.py", line 87, in <module>
    from gevent._hub_local import get_hub
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gevent/_util.py", line 105, in import_c_accel
    mod = importlib.import_module(cname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/__greenlet_primitives.pxd", line 12, in init gevent.__hub_local
ValueError: greenlet.greenlet has the wrong size, try recompiling. Expected 128, got 144

Any ideas?

Thanks,
Chris

**Comment by chrissweet** [comment]
Looks like the problem is "The problem is gevent<1.3.6 is broken with python 3.7” but if I install this,
hydrus 0.3.1 has requirement gevent==1.3.5, but you'll have gevent 1.3.6 which is incompatible.
hydrus 0.3.1 has requirement greenlet==0.4.13, but you'll have greenlet 0.4.16 which is incompatible.

!!!

Best,
Chris

**Comment by priyanshunayan** [comment]
@chrissweet  I tried reproducing this issue on my macOS 10.15.3 by using python version 3.7.0 and 3.7.3 but was not able to. It would be really helpful if you could specify python version you are using, and what steps you followed to run hydrus. Thank you.

**Comment by chrissweet** [comment]
Hi Priyanshu,

   I was using python 3.7.2, I will try an upgrade.

   I did get it running on a raspberry pi, had to port forward and the webpage laded with the graph. Couldn’t do get/post etc. though.

  I really appreciate your help!

Thanks,
Chris

**Comment by priyanshunayan** [comment]
@chrissweet If the graph was successfully loaded, you should be able to make all the operations. For reference you can refer the short tutorial (using the GUI part, you will have to scroll down a bit.) in the page: https://www.hydraecosystem.org/hydra-agent-redis-graph . Hope that helps!

**Comment by chrissweet** [comment]
Hi Priyanshu,

    Thank you, I had read through you excellent documentation! Looking
through the hydrus code it looks like it supports the socket io, I Had
assumed that was in the Agent. I will investigate further!

Thanks,
Chris

Sent from my iPad

On Jul 7, 2020, at 1:02 AM, Priyanshu Nayan <notifications@github.com>
wrote:

﻿

@chrissweet <https://github.com/chrissweet> If the graph was successfully
loaded, you should be able to make all the operations. For reference you
can refer the short tutorial (using the GUI part, you will have to scroll
down a bit.) in the page:
https://www.hydraecosystem.org/hydra-agent-redis-graph . Hope that helps!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/HTTP-APIs/hydra-python-agent-gui/issues/63#issuecomment-654601544>,
or unsubscribe

**Comment by chrizandr** [comment]
@priyanshunayan please close if resolved.
